### ISSUE TITLE
Pug

### ISSUE THREAD

**Issue by skinnynpale** [bigfatmoon/FSDBem#4]
Реализовать подключение и инициализацию всех скриптов для страницы в папке страницы в отдельном javascript файле

**Comment by skinnynpale** [comment]
Пример того как нельзя
![image](https://user-images.githubusercontent.com/52371356/83601153-3ae73900-a59a-11ea-9033-b4a9d8657892.png)

**Comment by bigfatmoon** [comment]
Не совсем поняла про то, как нельзя. Нельзя импортировать инициализацию там, где она не нужна, или нельзя вызывать инициализацию не в js файле блока-родителя?

**Comment by skinnynpale** [comment]
Убрать все такие index.js где подключаются стили. Стили нужно подключать в файле стилей к странице где используются 
![image](https://user-images.githubusercontent.com/52371356/84037410-c280dd80-a9c8-11ea-88d7-c69585a13a85.png)
